resources:
 repositories:
   - repository: templates
     type: git
     name: Cblx.Pipelines/templates

name: $(Build.SourceBranch)$(rev:.r)
trigger:
  - releases/*

variables:
  rev: $[counter(variables['Build.SourceBranch'], 0)]

stages:
# BUILD #####################################
- stage: Build
  displayName: Build
  jobs:
  #set build name
  - template: "set-build-name-job.yml@templates"
  #pack and publish artifact
  - template: "npm-pack.yml@templates"

# DEPLOY ###################################
#publish to cblx infra
- template: publish-to-npm.yml@templates
parameters:
  customFeed: 'd438802f-ab00-4d2e-940c-8c7593e1aad5'
