name: $(Build.SourceBranch)$(rev:.r)
trigger:
  - releases/*

variables:
  rev: $[counter(variables['Build.SourceBranch'], 0)]

stages:
# BUILD AND DEPLOY #####################################
- stage: BuildDeploy
  displayName: BuildAndDeploy
  jobs:
  #set build name
  - job: SetBuildName
    steps:
      - script: echo "##vso[build.updatebuildnumber]$(Build.SourceBranchName).$(Rev)"
        condition: contains(variables['Build.SourceBranch'], '/releases/')
      - script: echo "##vso[build.updatebuildnumber]0.0.0-$(Build.SourceBranchName).$(Rev)"
        condition: not(contains(variables['Build.SourceBranch'], '/releases/'))
      - script: npm install
      - script: tsc
      # deploy
      - script: npm version $(Build.BuildNumber) --no-git-tag-version
      - task: Npm@1
        inputs:
          command: 'publish'
          publishEndpoint: 'npmjs.org em nome de guilherme'
  
  
